%% femShaft - Generate FEM matrices for shaft components using Timoshenko beam theory
%
% This function assembles global mass, stiffness, gyroscopic, and nonlinear 
% matrices along with gravity vectors and unbalance data for multi-shaft 
% rotor systems using Timoshenko beam elements.
%
%% Syntax
%  [M, K, G, N, Fg, ShaftUnbalanceData] = femShaft(Shaft, nodeDistance, ShaftElements)
%
%% Description
% |femShaft| constructs finite element matrices for shaft components in 
% rotor dynamics models. The function:
% * Implements Timoshenko beam theory for annular shafts
% * Handles multi-shaft configurations
% * Accounts for distributed mass and stiffness
% * Includes gyroscopic and geometric nonlinear effects
% * Computes gravity loading
% * Aggregates distributed mass unbalance to nodes
%
%% Input Arguments
% * |Shaft| - Shaft properties structure:
%   * |amount|            % Number of shafts (scalar)
%   * |dofOfEachNodes|    % DOF per node [N×1 vector]
%   * |outerRadius|       % Outer radii [m] [N×1 vector]
%   * |innerRadius|       % Inner radii [m] [N×1 vector]
%   * |density|           % Material densities [kg/m³] [N×1 vector]
%   * |elasticModulus|    % Elastic moduli [Pa] [N×1 vector]
%   * |poissonRatio|      % Poisson's ratios [N×1 vector]
%   * N: Number of shaft segments
%
% * |nodeDistance|        % Node positions [cell array]:
%   * {i} = [d₁ d₂ ... dₘ] % Axial positions for shaft i [m]
%   * m: Number of nodes per shaft
%
% * |ShaftElements|       % Element definition structure array:
%   * Contains per-element properties (NodeNo, ShaftNo, geometry, unbalance)
%
%% Output Arguments
% * |M|  % Global mass matrix [sparse n×n]
% * |K|  % Global stiffness matrix [sparse n×n]
% * |G|  % Global gyroscopic matrix [sparse n×n]
% * |N|  % Global Transient matrix [sparse n×n]
% * |Fg| % Gravity force vector [n×1]
% * |ShaftUnbalanceData| % Unbalance data matrix [N_valid×3]:
%       Column 1: Node ID
%       Column 2: Magnitude [kg·m]
%       Column 3: Phase [rad]
%   * n: Total DOF of rotor system
%
%% Formulation
% Based on Timoshenko beam theory for annular shafts:
% 1. Element Matrices:
%   * Computed per shaft segment via |shaftElement|
%   * Accounts for:
%     - Translational and rotational inertia
%     - Shear deformation effects
%     - Rotary inertia
% 2. Geometric Nonlinearity:
%   * Captures stress-stiffening effects via |N| matrix
% 3. Unbalance Processing:
%   * Distributed unbalance is lumped to element nodes (50% each)
%   * Performs vector summation of contributions from adjacent elements
%   * Reconstructs net magnitude and phase per node
%
%% Assembly Process
% 1. Element-Level Generation:
%   * Computes element matrices (Me, Ke, Ge, Ne)
%   * Calculates element gravity (Fge) and unbalance vectors
% 2. Shaft-Level Assembly:
%   * Combines elements within each shaft using |assembleLinear|
%   * Maintains node connectivity
% 3. Global Assembly:
%   * Combines multi-shaft matrices diagonally
%   * Handles shaft-to-shaft connections
%
%% Implementation Details
% 1. Input Validation:
%   * Verifies shaft count matches node distance cells
% 2. Element Processing:
%   * Iterates through |ShaftElements| to generate matrices
% 3. Unbalance Handling:
%   * Accumulates X/Y components globally to handle phase differences correctly
%   * Returns only nodes with non-negligible unbalance (> 1e-15)
%
%% Example
% % Configure shaft parameters
% shaftCfg = struct('amount', 2, ...
%                  'dofOfEachNodes', [4; 4], ...
%                  'outerRadius', [0.05; 0.04], ...
%                  'innerRadius', [0; 0], ...
%                  'density', [7850; 7850], ...
%                  'elasticModulus', [210e9; 210e9], ...
%                  'rayleighDamping', [0, 1e-6],...
%                  'poissonRatio', [0.3; 0.3]);
% % Define node positions and elements (usually from meshModel)
% nodePos = {linspace(0, 1, 10), linspace(0, 0.8, 8)};
% % [Assume ShaftElements is generated by meshModel]
% % Generate FEM matrices
% [M, K, G, N, Fg, UnbalData] = femShaft(shaftCfg, nodePos, ShaftElements);
%
%% See Also
% shaftElement, assembleLinear, femDisk, femBearing, meshModel
%
% Copyright (c) 2021-2026 Haopeng Zhang, Northwestern Polytechnical University, Politecnico di Milano
% This code is licensed under the MIT License. See the LICENSE file in the project root for the full text of the license.
%


function [M, K, G, N, Fg, ShaftUnbalanceData] = femShaft(Shaft, nodeDistance, ShaftElements)

% Check input consistency
isMatch = Shaft.amount == length(nodeDistance);
if ~isMatch
    error('Dimension mismatch between Shaft amount and nodeDistance.');
end 

%% 1. Initialization
% Determine total node number to initialize global vectors
totalNodes = sum(cellfun(@length, nodeDistance));

% Initialize element matrix storage (Cell arrays by Shaft)
Me = cell(Shaft.amount,1); 
Ke = cell(Shaft.amount,1);
Ge = cell(Shaft.amount,1);
Ne = cell(Shaft.amount,1);
Fge = cell(Shaft.amount,1);

% Initialize Global Unbalance Accumulators (Vector Summation)
% We accumulate X and Y components to handle phase differences correctly.
Ux_Global = zeros(totalNodes, 1);
Uy_Global = zeros(totalNodes, 1);

%% 2. Element Generation Loop
for iShaft = 1:1:Shaft.amount
    
    % Filter elements belonging to the current shaft
    currentShaftElems = ShaftElements([ShaftElements.ShaftNo] == iShaft);
    elementNum = length(currentShaftElems);
    
    % Initialize storage for current shaft
    Me{iShaft} = cell(elementNum,1);
    Ke{iShaft} = cell(elementNum,1);
    Ge{iShaft} = cell(elementNum,1);
    Ne{iShaft} = cell(elementNum,1);
    Fge{iShaft} = cell(elementNum,1);
    
    for iElement = 1:1:elementNum
        % Extract single element data
        elemData = currentShaftElems(iElement);
        
        % Generate matrices for this element
        % [Updated] Now returns Unbalance Info
        [Me{iShaft}{iElement},...
         Ke{iShaft}{iElement},...
         Ge{iShaft}{iElement},...
         Ne{iShaft}{iElement},...
         Fge{iShaft}{iElement},...
         elemUnbal] = shaftElement(elemData);
     
        % --- Process Distributed Unbalance ---
        % Logic: Distributed unbalance (m*e) is lumped to the two nodes 
        % at the ends of the element (50% each).
        % We must perform VECTOR addition because adjacent elements might 
        % have different eccentricity phases.
        
        % Get Global Node IDs for this element
        nodeL = elemData.NodeNo(1);
        nodeR = elemData.NodeNo(2);
        
        % Calculate components (Half to each node)
        % U_half = 0.5 * Magnitude
        Ux_half = 0.5 * elemUnbal.Magnitude * cos(elemUnbal.Phase);
        Uy_half = 0.5 * elemUnbal.Magnitude * sin(elemUnbal.Phase);
        
        % Accumulate to Global Nodes
        Ux_Global(nodeL) = Ux_Global(nodeL) + Ux_half;
        Uy_Global(nodeL) = Uy_Global(nodeL) + Uy_half;
        
        Ux_Global(nodeR) = Ux_Global(nodeR) + Ux_half;
        Uy_Global(nodeR) = Uy_Global(nodeR) + Uy_half;
        
    end % end for iElement
end % end for iShaft

%% 3. Shaft-Level Assembly
MiShaft = cell(Shaft.amount,1);
KiShaft = cell(Shaft.amount,1);
GiShaft = cell(Shaft.amount,1);
NiShaft = cell(Shaft.amount,1);
FgiShaft = cell(Shaft.amount,1);

for iShaft = 1:1:Shaft.amount
    nodeNum = length(nodeDistance{iShaft});
    elementNum = nodeNum - 1;
    
    % Calculate intersection indices for assembly
    intersectRow = Shaft.dofOfEachNodes(iShaft) * ones(1,elementNum-1);
    intersectColumn = intersectRow;
    
    MiShaft{iShaft} = assembleLinear(Me{iShaft}, intersectRow, intersectColumn);
    KiShaft{iShaft} = assembleLinear(Ke{iShaft}, intersectRow, intersectColumn);
    GiShaft{iShaft} = assembleLinear(Ge{iShaft}, intersectRow, intersectColumn);
    NiShaft{iShaft} = assembleLinear(Ne{iShaft}, intersectRow, intersectColumn);
    FgiShaft{iShaft} = assembleLinear(Fge{iShaft}, intersectRow, ones(1,elementNum-1));
end

%% 4. Global System Assembly
% Assuming shafts are structurally decoupled in this matrix (coupled via bearings later)
intersectRow = zeros(1,Shaft.amount-1);
intersectColumn = zeros(1,Shaft.amount-1);

M = assembleLinear(MiShaft, intersectRow, intersectColumn);
K = assembleLinear(KiShaft, intersectRow, intersectColumn);
G = assembleLinear(GiShaft, intersectRow, intersectColumn);
N = assembleLinear(NiShaft, intersectRow, intersectColumn);
Fg = assembleLinear(FgiShaft, intersectRow, 1*ones(1,Shaft.amount-1));

%% 5. Process Shaft Unbalance Data (Compression)
% Convert accumulated X/Y components back to Magnitude and Phase
UnbalMag = sqrt(Ux_Global.^2 + Uy_Global.^2);
UnbalPhase = atan2(Uy_Global, Ux_Global);

% Filter nodes with non-zero unbalance (Threshold to avoid numerical noise)
tolerance = 1e-15;
validIndices = find(UnbalMag > tolerance);

% Construct Output Matrix: [NodeID, Magnitude, Phase]
ShaftUnbalanceData = [validIndices, UnbalMag(validIndices), UnbalPhase(validIndices)];

end % end function