%% hertzianForce - Calculate nonlinear Hertzian contact forces for bearings
%
% This function computes the nonlinear restoring forces generated by rolling 
% element bearings based on Hertzian contact theory. It accounts for the 
% relative displacement between inner and outer races and the time-varying 
% positions of rolling elements.
%
%% Syntax
%  fHertz = hertzianForce(qn, omega, HerzianParameter, dofNum)
%
%% Description
% |hertzianForce| iterates through all bearings designated as "Hertzian" 
% and calculates the resulting force vector. Key features include:
% * Support for both shaft-to-ground and shaft-to-shaft (intermediate) bearings
% * Calculation based on relative radial displacement: $\Delta x = x_i - x_o$
% * Integration of cage rotation effects via shaft angular phases
% * Mapping of local bearing forces to the global system DOF vector
%
%% Input Arguments
% * |qn| - Current system displacement vector [dofNum × 1]
% * |omega| - Angular phase vector for each shaft [shaftNum × 1]
% * |HerzianParameter| - Consolidated contact parameters (from |collectHerzianParameter|):
%   * |nb|: Number of rolling elements
%   * |ri|, |ro|: Race radii
%   * |delta0|: Radial clearance
%   * |kHertz|: Contact stiffness
%   * |n|: Load-deflection exponent
%   * |omegaiNo|, |omegaoNo|: Indices for inner/outer race rotation speed
%   * |hertzDof|: DOF mapping for inner and outer race pairs [N × 2]
%   * |hertzianNum|: Total number of Hertzian contact pairs
% * |dofNum| - Total number of system degrees of freedom
%
%% Output Arguments
% * |fHertz| - Global nonlinear force vector [dofNum × 1]
%
%% Implementation Notes
% * **Ground Connection Handling**: The function uses internal padding 
%   (adding virtual DOFs at |dofNum+1| and |dofNum+2|) to represent the 
%   ground as a stationary reference with zero displacement and rotation.
% * **Coordinate System**: The force is calculated based on relative 
%   displacement in the X and Y directions. The force applied to the 
%   inner shaft is $-F$, while the force on the outer shaft/ground is $+F$.
%
%% Dependencies
% * |hertzianForceEq| - Core equation for a single rolling element bearing
%
%% See Also
% collectHerzianParameter, dynamicEquation, hertzianForceJacobian
%
% Copyright (c) 2021-2026 Haopeng Zhang, Northwestern Polytechnical University, Politecnico di Milano
% This code is licensed under the MIT License. See the LICENSE file in the project root for the full text of the license.
%
function fHertz = hertzianForce(qn, omega, HerzianParameter, dofNum)

% load parameters
nb = HerzianParameter.nb;
ri = HerzianParameter.ri;
ro = HerzianParameter.ro;
delta0 = HerzianParameter.delta0;
kHertz = HerzianParameter.kHertz;
n = HerzianParameter.n;
omegaiNo = HerzianParameter.omegaiNo;
omegaoNo = HerzianParameter.omegaoNo;
hertzDof = HerzianParameter.hertzDof;
hertzianNum = HerzianParameter.hertzianNum;

omega = [omega, 0]; % add 1 row for adapting the bearing connecting the ground
qn = [qn; 0; 0]; % add 2 rows for adapting the bearing connecting the ground

fHertz2 = zeros(dofNum+2,1); % add 2 rows for adapting the bearing connecting the ground

for iHertz = 1:1:hertzianNum
    x = qn(hertzDof(iHertz,1)) - qn(hertzDof(iHertz,2)); % displacement of the Inner shaft - that of the Outer shaft
    y = qn(hertzDof(iHertz,1)+1) - qn(hertzDof(iHertz,2)+1);
    f = hertzianForceEq(x, y, omega(omegaiNo(iHertz)), omega(omegaoNo(iHertz)), nb(iHertz), ri(iHertz), ro(iHertz), delta0(iHertz), kHertz(iHertz), n(iHertz));
    fHertz2(hertzDof(iHertz,1):hertzDof(iHertz,1)+1) = -f; % the relative displacement is (x_Inner - x_Outer), so the force on the Inner shaft should add a minus "-".
    fHertz2(hertzDof(iHertz,2):hertzDof(iHertz,2)+1) = f; % the force on the outer shaft/ground
end

fHertz = fHertz2(1:end-2);

end